---
title: "8.2 Methods with trend"
output: html_document
date: '2022-04-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fpp3)
```

#### Holt's Linear trend method

$$
\text{Forecast equation} \; \hat{y}_{t+h|t} = l_t + h b_t \\
\text{Level equation} \; l_t = \alpha y_t + (1-\alpha)(l_{t-1} + b_{t-1}) \\
\text{Trend equation} \; b_t = \beta^*(l_t - l_{t-1}) + (1-\beta^*)b_{t-1} \\
\text{where} \\
\;\; l_t :\text{Level at time $t$} \\
\;\; b_t :\text{Trend at time $t$} \\
\;\; \alpha : \text{Smoothing parameter for Level} \\
\;\; \beta^* : \text{Smoothing parameter for Trend} 
$$

#### Example: Australian population

```{r}
aus_economy <- global_economy %>%
  filter(Code == "AUS") %>%
  mutate(Pop = Population / 1e6)

autoplot(aus_economy, Pop) +
  labs(y = "Millions", title = "Australian population")
```

```{r}
fit <- aus_economy %>%
  model(
    AAN = ETS(Pop ~ error("A") + trend("A") + season("N"))
  )

fc <- fit %>% forecast(h = 10)
```

#### Damped trend methods

$$
\text{Forecast equation} \; \hat{y}_{t+h} = l_t + (\phi+\phi^2+\dots+\phi^h)b_t \\
\text{Level equation} \; l_t = \alpha y_t + (1-\alpha)(l_{t-1} + \phi b_{t-1}) \\
\text{Trend equation} \; b_t = \beta^*(l_t - l_{t-1}) + (1-\beta^*)\phi b_{t-1}
$$

#### 

Example: Australian Population (continued)

```{r}
aus_economy %>%
  model(
    `Holt's method` = ETS(Pop ~ error("A") +
                       trend("A") + season("N")),
    `Damped Holt's method` = ETS(Pop ~ error("A") +
                       trend("Ad", phi = 0.9) + season("N"))
  ) %>%
  forecast(h = 15) %>%
  autoplot(aus_economy, level = NULL) +
  labs(title = "Australian population",
       y = "Millions") +
  guides(colour = guide_legend(title = "Forecast"))
```

#### Example: Internet usage

```{r}
www_usage <- as_tsibble(WWWusage)

www_usage %>% autoplot(value) +
  labs(x="Minute", y="Number of users",
       title = "Internet usage per minute")
```

```{r}
www_usage %>%
  stretch_tsibble(.init = 10) %>%
  model(
    SES = ETS(value ~ error("A") + trend("N") + season("N")),
    Holt = ETS(value ~ error("A") + trend("A") + season("N")),
    Damped = ETS(value ~ error("A") + trend("Ad") + season("N"))
  ) %>%
  forecast(h = 1) %>%
  
  accuracy(www_usage)

```

```{r}
fit <- www_usage %>%
  model(Damped = ETS(value ~ error("A") + trend("Ad") + season("N")))

# Estimated parameters:
tidy(fit)
```

```{r}
fit %>%
  forecast(h = 10) %>%
  autoplot(www_usage) +
  labs(x="Minute", y="Number of users",
       title = "Internet usage per minute")
```
