---
title: "9.10 ARIMA vs ETS"
output: html_document
date: '2022-04-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fpp3)
```


#### Comparing ARIMA() and ETS() on non-seasonal data

```{r}
aus_economy <- global_economy %>%
  filter(Code == "AUS") %>%
  mutate(Population = Population/1e6)

aus_economy %>%
  slice(-n()) %>%
  stretch_tsibble(.init = 10) %>%
  model(
    ETS(Population),
    ARIMA(Population)
  ) %>%
  forecast(h = 1) %>%
  accuracy(aus_economy) %>%
  select(.model, RMSE:MAPE)

```

```{r}
aus_economy %>%
  model(ETS(Population)) %>%
  forecast(h = "5 years") %>%
  autoplot(aus_economy %>% filter(Year >= 2000)) +
  labs(title = "Australian population",
       y = "People (millions)")
```


#### Comparing ARIMA() and ETS() on seasonal data

```{r}
cement <- aus_production %>%
  select(Cement) %>%
  filter_index("1988 Q1" ~ .)

train <- cement %>% filter_index(. ~ "2007 Q4")
```


```{r}
fit_arima <- train %>% model(ARIMA(Cement))
report(fit_arima)
```

```{r}
fit_arima %>% gg_tsresiduals(lag_max = 16)

```

```{r}
augment(fit_arima) %>%
  features(.innov, ljung_box, lag = 16, dof = 6)

```

```{r}
fit_ets <- train %>% model(ETS(Cement))
report(fit_ets)
```


```{r}
fit_ets %>%
  gg_tsresiduals(lag_max=16)
```


```{r}
# Generate forecasts and compare accuracy over the test set
bind_rows(
    fit_arima %>% accuracy(),
    fit_ets %>% accuracy(),
    fit_arima %>% forecast(h = 10) %>% accuracy(cement),
    fit_ets %>% forecast(h = 10) %>% accuracy(cement)
  ) %>%
  select(-ME, -MPE, -ACF1)
```


```{r}
cement %>%
  model(ARIMA(Cement)) %>%
  forecast(h="3 years") %>%
  autoplot(cement) +
  labs(title = "Cement production in Australia",
       y = "Tonnes ('000)")
```

