---
title: "7.7 Nonlinear regression"
output: html_document
date: '2022-04-07'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(fpp3)
```

- Log linear model
  - transformation on the forecast variable and/or the predictor variable
    - log-log form
    - log-linear form
    - linear-log form

- Piecewise linear model
  - Introduce points where the slope of f can change by 

- Regression splines

#### Forecasting with a nonlinear trend

#### Example: Boston marathon winning times

```{r}
boston_men <- boston_marathon %>%
  filter(Year >= 1924) %>%
  filter(Event == "Men's open division") %>%
  mutate(Minutes = as.numeric(Time)/60)

boston_men %>% 
  autoplot(Minutes) +
  geom_smooth(method="lm")
```


```{r}
fit_trends <- boston_men %>%
  model(
    linear = TSLM(Minutes ~ trend()),
    exponential = TSLM(log(Minutes) ~ trend()),
    piecewise = TSLM(Minutes ~ trend(knots = c(1950, 1980)))
  )

fc_trends <- fit_trends %>% forecast(h = 10)

boston_men %>%
  autoplot(Minutes) +
  geom_line(data = fitted(fit_trends),
            aes(y = .fitted, colour = .model)) +
  autolayer(fc_trends, alpha = 0.5, level = 95) +
  labs(y = "Minutes",
       title = "Boston marathon winning times")
```

